### ISSUE TITLE
Get more out of query errors...

### ISSUE THREAD

**Issue by langdonx** [mattbit/mysql-compat#9]
From `mysql-compat/src/Connection.php:43`
```
        $statement = $this->pdo->query($query);

        if ($statement === false) {
            throw new QueryException('Error executing the query.');
        }
```

For easier backwards compatability and troubleshooting, this might be more helpful if `$this.getErrorInfo()` were sent along with the exception.

As it is now, I don't seemingly have a way to get any error information myself, since I don't have access to the Connection from my calling code.

I ran into this because while `select id, id from table` works just fine, PDO apparently has an issue with the duplicate field.

I'm using this for now has a hack-fix:

> `throw new QueryException('Query error ' . serialize($this->getErrorInfo()));`

**Comment by mattbit** [comment]
Hi @langdonx, thanks for raising the issue. It's not very clear to me how you obtain the `QueryException` object. Could you provide a code example?

In principle, if you are using the replacement for the global mysql functions, you should never see a `QueryException`, since it should be caught here:

https://github.com/mattbit/mysql-compat/blob/5476660f36b71f5ee6448cd0a5df43c8e81696b2/src/BridgeComponents/ExecuteQueries.php#L23

That's because the old mysql functions did not throw exceptions if the query failed but instead returned `false` (the error could be recovered with `mysql_error`).

Also, note that you can always access the connection manager using `Mysql::getManager` and retrieve the most recent connection:

```php
use Mattbit\MysqlCompat\Mysql;

$manager = Mysql::getManager();
$connection = $manager->getLastConnection();
```

**Comment by langdonx** [comment]
It looks like it's not being handled here:

https://github.com/mattbit/mysql-compat/blob/master/src/BridgeComponents/FetchResults.php#L107

```
Uncaught Mattbit\MysqlCompat\Exception\QueryException: Query error a:3:{i:0;s:5:&quot;42S21&quot;;i:1;i:1060;i:2;s:37:&quot;Duplicate column name 'z'&quot;;} in /home/.../mattbit/mysql-compat/src/Connection.php:48
Stack trace:
#0 /home/.../mattbit/mysql-compat/src/BridgeComponents/FetchResults.php(108): Mattbit\MysqlCompat\Connection-&gt;query('SELECT COUNT(*)...')
#1 [internal function]: Mattbit\MysqlCompat\Bridge-&gt;numRows(Object(Mattbit\MysqlCompat\Result))
#2 /home/.../mattbit/mysql-compat/src/Mysql.php(40): call_user_func_array(Array, Array)
#3 /home/.../mattbit/mysql-compat/src/globals.php(166): Mattbit\MysqlCompat\Mysql::__callStatic('numRows', Array)
...
```

ETA: Thank you for pointing out `getLastConnection()`, that will be quite helpful.

**Comment by mattbit** [comment]
> It looks like it's not being handled here:
> 
> https://github.com/mattbit/mysql-compat/blob/master/src/BridgeComponents/FetchResults.php#L107

Oh, that's a bug that must be fixed: it should return `false` as the original `mysql_num_rows`.

> ETA: Thank you for pointing out `getLastConnection()`, that will be quite helpful.

Great!

Since `QueryException` is not supposed to be exposed to the user, it is quite useless to send the error with it. Instead, you have several ways to retrieve the error:

```php
$error = Mysql::error();

// or (if globals were registered)
$error = mysql_error();

// or (to get the full PDO::errorInfo)
$errorInfo = Mysql::getManager()->getLastConnection()->getErrorInfo();
```

If this is fine for you, I'll close the issue.

**Comment by langdonx** [comment]
Yep, those approaches are all perfect!  Thanks & closed.
